baseurl = "/"
title = "The Archives"
author = "Lazar!!"
copyright = "I don't really care. "
canonifyurls = true
paginate = 4
theme = "newsprint"

[params]

subtitle = "Everything here at once."

[[menu.main]]
  name = "🛩 🛳 My Travel Journal 🗻"
  weight = 9
  identifier = "travel"
  url = "https://travel.lazarmarlin.tk"
